### ISSUE TITLE
Use of deprecated Any::Moose

### ISSUE THREAD

**Issue by karenetheridge** [bluefeet/GIS-Distance#2]
As documented, this is now deprecated in favour of Moo.

see http://shadow.cat/blog/matt-s-trout/moo-versus-any-moose/ for an explanation of why Any::Moose is broken by design.

https://metacpan.org/pod/Any::Moose#DEPRECATION
日本語翻訳: http://blog.64p.org/entry/2013/02/06/094906

**Comment by bluefeet** [comment]
Its been on my todo for a while to change this to Moo.  Will take a look while @ YAPC.

**Comment by bluefeet** [comment]
Resolve in v0.09.
